export enum PERMISSIONS {
  VIEW_ADMINS = "VIEW_ADMINS",
  VIEW_ADMIN = "VIEW_ADMIN",
  CREATE_ADMIN = "CREATE_ADMIN",
  UPDATE_ADMIN = "UPDATE_ADMIN",
  DELETE_ADMIN = "DELETE_ADMIN",

  VIEW_USERS = "VIEW_USERS",
  VIEW_USER = "VIEW_USER",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",

  VIEW_ROLES = "VIEW_ROLES",
  VIEW_ROLE = "VIEW_ROLE",
  CREATE_ROLE = "CREATE_ROLE",
  UPDATE_ROLE = "UPDATE_ROLE",
  DELETE_ROLE = "DELETE_ROLE",

  VIEW_BLOGS = "VIEW_BLOGS",
  VIEW_BLOG = "VIEW_BLOG",
  CREATE_BLOG = "CREATE_BLOG",
  UPDATE_BLOG = "UPDATE_BLOG",
  DELETE_BLOG = "DELETE_BLOG",

  VIEW_BANNERS = "VIEW_BANNERS",
  VIEW_BANNER = "VIEW_BANNER",
  CREATE_BANNER = "CREATE_BANNER",
  UPDATE_BANNER = "UPDATE_BANNER",
  DELETE_BANNER = "DELETE_BANNER",

  VIEW_NETWORKS = "VIEW_NETWORKS",
  VIEW_NETWORK = "VIEW_NETWORK",
  CREATE_NETWORK = "CREATE_NETWORK",
  UPDATE_NETWORK = "UPDATE_NETWORK",
  DELETE_NETWORK = "DELETE_NETWORK",

  VIEW_PAGE_INFOS = "VIEW_PAGE_INFOS",
  VIEW_PAGE_INFO = "VIEW_PAGE_INFO",
  CREATE_PAGE_INFO = "CREATE_PAGE_INFO",
  UPDATE_PAGE_INFO = "UPDATE_PAGE_INFO",
  DELETE_PAGE_INFO = "DELETE_PAGE_INFO",

  VIEW_OPEN_DATAS = "VIEW_OPEN_DATAS",
  VIEW_OPEN_DATA = "VIEW_OPEN_DATA",
  CREATE_OPEN_DATA = "CREATE_OPEN_DATA",
  UPDATE_OPEN_DATA = "UPDATE_OPEN_DATA",
  DELETE_OPEN_DATA = "DELETE_OPEN_DATA",

  VIEW_MANAGEMENTS = "VIEW_MANAGEMENTS",
  VIEW_MANAGEMENT = "VIEW_MANAGEMENT",
  CREATE_MANAGEMENT = "CREATE_MANAGEMENT",
  UPDATE_MANAGEMENT = "UPDATE_MANAGEMENT",
  DELETE_MANAGEMENT = "DELETE_MANAGEMENT",

  VIEW_DISTRICTS = "VIEW_DISTRICTS",
  VIEW_DISTRICT = "VIEW_DISTRICTS",
  CREATE_DISTRICT = "CREATE_DISTRICT",
  UPDATE_DISTRICT = "UPDATE_DISTRICT",
  DELETE_DISTRICT = "UPDATE_DISTRICT",

  VIEW_WORK_ORDERS = "VIEW_WORK_ORDERS",
  VIEW_WORK_ORDER = "VIEW_WORK_ORDER",
  CREATE_WORK_ORDER = "CREATE_WORK_ORDER",
  UPDATE_WORK_ORDER = "UPDATE_WORK_ORDER",
  DELETE_WORK_ORDER = "DELETE_WORK_ORDER",

  VIEW_CONTACT_USES = "VIEW_CONTACT_USES",
  VIEW_CONTACT_US = "VIEW_CONTACT_US",
  CREATE_CONTACT_US = "CREATE_CONTACT_US",
  UPDATE_CONTACT_US = "UPDATE_CONTACT_US",
  DELETE_CONTACT_US = "DELETE_CONTACT_US",
  CREATE_OR_UPDATE_CONTACT_US = "CREATE_OR_UPDATE_CONTACT_US",

  VIEW_CENTRAL_APPARATUSES = "VIEW_CENTRAL_APPARATUSES",
  VIEW_CENTRAL_APPARATUS = "VIEW_CENTRAL_APPARATUS",
  CREATE_CENTRAL_APPARATUS = "CREATE_CENTRAL_APPARATUS",
  UPDATE_CENTRAL_APPARATUS = "UPDATE_CENTRAL_APPARATUS",
  DELETE_CENTRAL_APPARATUS = "DELETE_CENTRAL_APPARATUS",

  VIEW_TRANSLATIONS = "VIEW_TRANSLATIONS",
  VIEW_TRANSLATION = "VIEW_TRANSLATION",
  CREATE_TRANSLATION = "CREATE_TRANSLATION",
  UPDATE_TRANSLATION = "UPDATE_TRANSLATION",
  DELETE_TRANSLATION = "DELETE_TRANSLATION",
}

export enum FILE_TYPE {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  AUDIO = "AUDIO",
  FILE = "FILE",
}

export enum MESSAGE_TYPE {
  INFO = "INFO",
  WARNING = "WARNING",
  ERROR = "ERROR",
}
